version: '3'

services:

  portainer:
    image: portainer/portainer:1.15.0
    command: --no-auth -H unix:///var/run/docker.sock
    
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - 9000:9000

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - type: bind
      #   source: "/var/run/docker.sock"
      #   target: "/var/run/docker.sock"
      
  visualizer:
    image: dockersamples/visualizer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          
      placement:
        constraints:
          - node.role == manager
          
    ports:
      - 8080:8080

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - type: bind
      #   source: "/var/run/docker.sock"
      #   target: "/var/run/docker.sock"    
