version: '3'

services:

  elasticsearch:
    image: "bennyr/elasticsearch:6.2.1"
    #image: "docker.elastic.co/elasticsearch/elasticsearch:6.1.1"
    #image: "bennyr/esalpinecors"
    #image: "bennyr/elasticsearch:5.6.4-alpine"
    environment:
      - SERVICE_NAME=elasticsearch
#      - cluster.name=docker-cluster
#      - bootstrap.memoryy_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
#      - http.cors.enabled="true"
#      - http.cors.allow-origin="*"

    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.type == eshost
      #resources:
      #  limits:
      #    memory: 4G

    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

    networks:
      - esnet

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.2.1"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

    ports:
      - 5601:5601

    networks:
      - esnet

    depends_on:
      - "elasticsearch"

  elastiflow:

    image: bennyr/esftest

    environment:
      - PATH_CONFIG=/etc/logstash/elastiflow/conf.d
      - ELASTIFLOW_GEOIP_DB_PATH=/etc/logstash/elastiflow/geoipdbs
      - ELASTIFLOW_DICT_PATH=/etc/logstash/elastiflow/dictionaries
      - ELASTIFLOW_TEMPLATE_PATH=/etc/logstash/elastiflow/templates

      - ELASTIFLOW_RESOLVE_IP2HOST=false
      - ELASTIFLOW_NAMESERVER=127.0.0.1

      #- ELASTIFLOW_ES_HOST=127.0.0.1
      - ELASTIFLOW_ES_HOST=elasticsearch
      #- ELASTIFLOW_ES_HOST=10.175.98.133
      - ELASTIFLOW_ES_USER=elastic
      - ELASTIFLOW_ES_PASSWD=changeme

      - ELASTIFLOW_NETFLOW_HOST=0.0.0.0
      - ELASTIFLOW_NETFLOW_PORT=2055
      - ELASTIFLOW_NETFLOW_LASTSW_TIMESTAMP=false
      - ELASTIFLOW_NETFLOW_TZ=UTC

      - ELASTIFLOW_SFLOW_HOST=0.0.0.0
      - ELASTIFLOW_SFLOW_PORT=6343

      - ELASTIFLOW_IPFIX_TCP_HOST=0.0.0.0
      - ELASTIFLOW_IPFIX_TCP_PORT=4739
      - ELASTIFLOW_IPFIX_UDP_HOST=0.0.0.0
      - ELASTIFLOW_IPFIX_UDP_PORT=4739

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

    ports:
      - "2055:2055"
      - "6343:6343"
      - "4739:4739"
     
    networks:
      - esnet
     
volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: overlay
