  # 218  yum install python3 python34-setuptools
  # 219  easy_install-3.4 pip
  # 220  pip3 install esrally
---
- hosts: all
  become: true
  tasks:

    - name: Install python3
      yum:
        name: python34
        state: present
        update_cache: yes

    - name: Install python3 tools
      yum:
        name: python34-setuptools
        state: present
        update_cache: yes

    - name: Install python3 devel
      yum:
        name: python34-devel
        state: present
        update_cache: yes
        
    - name: Install pip
      shell:
        /usr/bin/easy_install-3.4 pip
      args:
        creates: /usr/bin/pip3

    - name: Install esrally
      shell:
        /usr/bin/pip3 install esrally
      args:
        creates: /usr/bin/esrally
